### ISSUE TITLE
Create reactions for input to input connections spanning hierarchical components. Will help with mutations. 

### ISSUE THREAD

**Issue by mew2ub** [icyphy/reactor-ts#41]

**Comment by lhstrh** [comment]
This approach simplified the formalism, but in our implementation it's fine to stick to the push semantics as long as:
- mutations can "repudiate" reactions by marking them as inactive, and inactive reactions on the reaction queue are not executed; and
- reactions don't execute ahead of mutations that can affect their inputs/triggers.
